### ISSUE TITLE
Error: The Angular AoT build failed

### ISSUE THREAD

**Issue by engmmrj** [eakoriakin/ionic-select-searchable#2]
I use ionic-select-searchable in my project. 
I have received an error when build release for Android but i run `ionic serve` my project is correct and does not any error

ionic-select-searchable has a problem while build release

error: `$ ionic cordova build android --prod --release
Running app-scripts build: --prod --platform android --target cordova
[16:01:15]  build prod started ... 
[16:01:15]  clean started ... 
[16:01:15]  clean finished in 2 ms 
[16:01:15]  copy started ... 
[16:01:15]  deeplinks started ... 
[16:01:15]  deeplinks finished in 131 ms 
[16:01:15]  ngc started ... 
[16:01:20]  typescript error 
            Unexpected value 'SelectSearchableModule in 
            /home/mahdi/apps/jensa/node_modules/ionic-select-searchable/source/select-searchable.module.d.ts' imported 
            by the module 'AppModule in /home/mahdi/apps/jensa/src/app/app.module.ts'. Please add a @NgModule 
            annotation. 

Error: The Angular AoT build failed. See the issues above
    at /home/mahdi/apps/jensa/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:237:55
    at step (/home/mahdi/apps/jensa/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:32:23)
    at Object.next (/home/mahdi/apps/jensa/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:13:53)
    at fulfilled (/home/mahdi/apps/jensa/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:4:58)
[16:01:20]  copy finished in 5.20 s 
`

**Comment by eakoriakin** [comment]
Hello @engmmrj, yes, versions prior to 1.0.9, have this problem.
Please, intall ionic-select-searchable@1.0.9:
`npm i ionic-select-searchable@1.0.9`

**Comment by dmitri-wm** [comment]
@eakoriakin thanks for this lib, saved me time :+1:

**Comment by eakoriakin** [comment]
@dmitri-wm, you are welcome :)

**Comment by engmmrj** [comment]
I have build apk for Android but it does not work on my Android device.
I have recorded a screencast on my Android device.
[https://streamable.com/mwtzo](url)

**Comment by eakoriakin** [comment]
Hey, how do you build it? Can you try using --release flag, instead of --prod?

**Comment by eakoriakin** [comment]
Hey @engmmrj  can you try `1.0.14` version? Let me know if it works for you.
